### ISSUE TITLE
Editing a node throws an exception error 

### ISSUE THREAD

**Issue by giftakari** [dpc-sdp/tide_core#397]
If a user  tries to edit a node with any number , an exception is thrown. 

How to replicate the error

Click on myworkbench
type "farm" in the search and then search 
click the farm result 
click on the "edit" button
in the weight , edit it and type a number 10 and above 
click on preview 
An error is shown 

<img width="936" alt="2023-04-06_12-23-44" src="https://user-images.githubusercontent.com/37270379/231610586-1e345d03-fa1f-472e-b3c0-94ece195e3c5.png">
<img width="960" alt="Can't_edit_node" src="https://user-images.githubusercontent.com/37270379/231610592-4d543bc3-29b3-4f64-8c71-10d486a60530.png">

**Comment by MdNadimHossain** [comment]
Hi @giftakari 
the issue here is, this custom content type missing the content moderation. The quick fix, add it to workflow from ui in production and then export the configs in a PR branch and merge to development branches, so it gets deployed to production in the next deployment. 
This is the place from UI - /admin/config/workflow/workflows/manage/editorial?destination=/admin/config/workflow/workflows
<img width="1488" alt="Screenshot 2023-04-13 at 11 05 17 am" src="https://user-images.githubusercontent.com/20810541/231619266-c490b5c1-14c7-4d64-b083-5d328a31eb36.png">

You can also raise a ticket if you see these kinds of issue from the support board. Here are the instructions you can follow to raise a ticket - https://www.vic.gov.au/how-raise-support-ticket

**Comment by giftakari** [comment]
Works perfectly. 

Thanks
